/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ActorDTO } from './ActorDTO';
import {
    ActorDTOFromJSON,
    ActorDTOFromJSONTyped,
    ActorDTOToJSON,
} from './ActorDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ActorDTORequestResponse
 */
export interface ActorDTORequestResponse {
    /**
     * 
     * @type {ActorDTO}
     * @memberof ActorDTORequestResponse
     */
    response?: ActorDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ActorDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ActorDTORequestResponse interface.
 */
export function instanceOfActorDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ActorDTORequestResponseFromJSON(json: any): ActorDTORequestResponse {
    return ActorDTORequestResponseFromJSONTyped(json, false);
}

export function ActorDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActorDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ActorDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ActorDTORequestResponseToJSON(value?: ActorDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ActorDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

