/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ActorDTO } from './ActorDTO';
import {
    ActorDTOFromJSON,
    ActorDTOFromJSONTyped,
    ActorDTOToJSON,
} from './ActorDTO';

/**
 * 
 * @export
 * @interface ActorDTOPagedResponse
 */
export interface ActorDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof ActorDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ActorDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ActorDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<ActorDTO>}
     * @memberof ActorDTOPagedResponse
     */
    data?: Array<ActorDTO> | null;
}

/**
 * Check if a given object implements the ActorDTOPagedResponse interface.
 */
export function instanceOfActorDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ActorDTOPagedResponseFromJSON(json: any): ActorDTOPagedResponse {
    return ActorDTOPagedResponseFromJSONTyped(json, false);
}

export function ActorDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActorDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(ActorDTOFromJSON)),
    };
}

export function ActorDTOPagedResponseToJSON(value?: ActorDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(ActorDTOToJSON)),
    };
}

