/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GenderEnum } from './GenderEnum';
import {
    GenderEnumFromJSON,
    GenderEnumFromJSONTyped,
    GenderEnumToJSON,
} from './GenderEnum';

/**
 * 
 * @export
 * @interface ActorUpdateDTO
 */
export interface ActorUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateDTO
     */
    firstName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateDTO
     */
    lastName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ActorUpdateDTO
     */
    birthdate?: Date | null;
    /**
     * 
     * @type {GenderEnum}
     * @memberof ActorUpdateDTO
     */
    gender?: GenderEnum;
    /**
     * 
     * @type {string}
     * @memberof ActorUpdateDTO
     */
    photoUrl?: string | null;
}

/**
 * Check if a given object implements the ActorUpdateDTO interface.
 */
export function instanceOfActorUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ActorUpdateDTOFromJSON(json: any): ActorUpdateDTO {
    return ActorUpdateDTOFromJSONTyped(json, false);
}

export function ActorUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActorUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'birthdate': !exists(json, 'birthdate') ? undefined : (json['birthdate'] === null ? null : new Date(json['birthdate'])),
        'gender': !exists(json, 'gender') ? undefined : GenderEnumFromJSON(json['gender']),
        'photoUrl': !exists(json, 'photoUrl') ? undefined : json['photoUrl'],
    };
}

export function ActorUpdateDTOToJSON(value?: ActorUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'firstName': value.firstName,
        'lastName': value.lastName,
        'birthdate': value.birthdate === undefined ? undefined : (value.birthdate === null ? null : value.birthdate.toISOString()),
        'gender': GenderEnumToJSON(value.gender),
        'photoUrl': value.photoUrl,
    };
}

