/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ActorDTOPagedResponse } from './ActorDTOPagedResponse';
import {
    ActorDTOPagedResponseFromJSON,
    ActorDTOPagedResponseFromJSONTyped,
    ActorDTOPagedResponseToJSON,
} from './ActorDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface ActorDTOPagedResponseRequestResponse
 */
export interface ActorDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {ActorDTOPagedResponse}
     * @memberof ActorDTOPagedResponseRequestResponse
     */
    response?: ActorDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ActorDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ActorDTOPagedResponseRequestResponse interface.
 */
export function instanceOfActorDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ActorDTOPagedResponseRequestResponseFromJSON(json: any): ActorDTOPagedResponseRequestResponse {
    return ActorDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ActorDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActorDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ActorDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ActorDTOPagedResponseRequestResponseToJSON(value?: ActorDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ActorDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

