/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { MovieDTOPagedResponse } from './MovieDTOPagedResponse';
import {
    MovieDTOPagedResponseFromJSON,
    MovieDTOPagedResponseFromJSONTyped,
    MovieDTOPagedResponseToJSON,
} from './MovieDTOPagedResponse';

/**
 * 
 * @export
 * @interface MovieDTOPagedResponseRequestResponse
 */
export interface MovieDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {MovieDTOPagedResponse}
     * @memberof MovieDTOPagedResponseRequestResponse
     */
    response?: MovieDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof MovieDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the MovieDTOPagedResponseRequestResponse interface.
 */
export function instanceOfMovieDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MovieDTOPagedResponseRequestResponseFromJSON(json: any): MovieDTOPagedResponseRequestResponse {
    return MovieDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function MovieDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : MovieDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function MovieDTOPagedResponseRequestResponseToJSON(value?: MovieDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': MovieDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

