/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ActorDTO } from './ActorDTO';
import {
    ActorDTOFromJSON,
    ActorDTOFromJSONTyped,
    ActorDTOToJSON,
} from './ActorDTO';
import type { StaffDTO } from './StaffDTO';
import {
    StaffDTOFromJSON,
    StaffDTOFromJSONTyped,
    StaffDTOToJSON,
} from './StaffDTO';

/**
 * 
 * @export
 * @interface MovieDTO
 */
export interface MovieDTO {
    /**
     * 
     * @type {string}
     * @memberof MovieDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MovieDTO
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof MovieDTO
     */
    releaseDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof MovieDTO
     */
    language?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MovieDTO
     */
    genre?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MovieDTO
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MovieDTO
     */
    rating?: number;
    /**
     * 
     * @type {number}
     * @memberof MovieDTO
     */
    numberOfRatings?: number;
    /**
     * 
     * @type {string}
     * @memberof MovieDTO
     */
    duration?: string | null;
    /**
     * 
     * @type {Array<ActorDTO>}
     * @memberof MovieDTO
     */
    actors?: Array<ActorDTO> | null;
    /**
     * 
     * @type {Array<StaffDTO>}
     * @memberof MovieDTO
     */
    staffMembers?: Array<StaffDTO> | null;
}

/**
 * Check if a given object implements the MovieDTO interface.
 */
export function instanceOfMovieDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MovieDTOFromJSON(json: any): MovieDTO {
    return MovieDTOFromJSONTyped(json, false);
}

export function MovieDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'releaseDate': !exists(json, 'releaseDate') ? undefined : (new Date(json['releaseDate'])),
        'language': !exists(json, 'language') ? undefined : json['language'],
        'genre': !exists(json, 'genre') ? undefined : json['genre'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'numberOfRatings': !exists(json, 'numberOfRatings') ? undefined : json['numberOfRatings'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'actors': !exists(json, 'actors') ? undefined : (json['actors'] === null ? null : (json['actors'] as Array<any>).map(ActorDTOFromJSON)),
        'staffMembers': !exists(json, 'staffMembers') ? undefined : (json['staffMembers'] === null ? null : (json['staffMembers'] as Array<any>).map(StaffDTOFromJSON)),
    };
}

export function MovieDTOToJSON(value?: MovieDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'releaseDate': value.releaseDate === undefined ? undefined : (value.releaseDate.toISOString()),
        'language': value.language,
        'genre': value.genre,
        'imageUrl': value.imageUrl,
        'rating': value.rating,
        'numberOfRatings': value.numberOfRatings,
        'duration': value.duration,
        'actors': value.actors === undefined ? undefined : (value.actors === null ? null : (value.actors as Array<any>).map(ActorDTOToJSON)),
        'staffMembers': value.staffMembers === undefined ? undefined : (value.staffMembers === null ? null : (value.staffMembers as Array<any>).map(StaffDTOToJSON)),
    };
}

