/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { MovieDTO } from './MovieDTO';
import {
    MovieDTOFromJSON,
    MovieDTOFromJSONTyped,
    MovieDTOToJSON,
} from './MovieDTO';

/**
 * 
 * @export
 * @interface MovieDTOListRequestResponse
 */
export interface MovieDTOListRequestResponse {
    /**
     * 
     * @type {Array<MovieDTO>}
     * @memberof MovieDTOListRequestResponse
     */
    readonly response?: Array<MovieDTO> | null;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof MovieDTOListRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the MovieDTOListRequestResponse interface.
 */
export function instanceOfMovieDTOListRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MovieDTOListRequestResponseFromJSON(json: any): MovieDTOListRequestResponse {
    return MovieDTOListRequestResponseFromJSONTyped(json, false);
}

export function MovieDTOListRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieDTOListRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : (json['response'] === null ? null : (json['response'] as Array<any>).map(MovieDTOFromJSON)),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function MovieDTOListRequestResponseToJSON(value?: MovieDTOListRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

