/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MovieDTO } from './MovieDTO';
import {
    MovieDTOFromJSON,
    MovieDTOFromJSONTyped,
    MovieDTOToJSON,
} from './MovieDTO';

/**
 * 
 * @export
 * @interface MovieDTOPagedResponse
 */
export interface MovieDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof MovieDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof MovieDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof MovieDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<MovieDTO>}
     * @memberof MovieDTOPagedResponse
     */
    data?: Array<MovieDTO> | null;
}

/**
 * Check if a given object implements the MovieDTOPagedResponse interface.
 */
export function instanceOfMovieDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MovieDTOPagedResponseFromJSON(json: any): MovieDTOPagedResponse {
    return MovieDTOPagedResponseFromJSONTyped(json, false);
}

export function MovieDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(MovieDTOFromJSON)),
    };
}

export function MovieDTOPagedResponseToJSON(value?: MovieDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(MovieDTOToJSON)),
    };
}

