/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MovieUpdateDTO
 */
export interface MovieUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof MovieUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MovieUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MovieUpdateDTO
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof MovieUpdateDTO
     */
    releaseDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof MovieUpdateDTO
     */
    language?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MovieUpdateDTO
     */
    genre?: string | null;
    /**
     * 
     * @type {string}
     * @memberof MovieUpdateDTO
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof MovieUpdateDTO
     */
    rating?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MovieUpdateDTO
     */
    numberOfRatings?: number | null;
    /**
     * 
     * @type {string}
     * @memberof MovieUpdateDTO
     */
    duration?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof MovieUpdateDTO
     */
    actorsIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof MovieUpdateDTO
     */
    staffMembersIds?: Array<string> | null;
}

/**
 * Check if a given object implements the MovieUpdateDTO interface.
 */
export function instanceOfMovieUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MovieUpdateDTOFromJSON(json: any): MovieUpdateDTO {
    return MovieUpdateDTOFromJSONTyped(json, false);
}

export function MovieUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'releaseDate': !exists(json, 'releaseDate') ? undefined : (json['releaseDate'] === null ? null : new Date(json['releaseDate'])),
        'language': !exists(json, 'language') ? undefined : json['language'],
        'genre': !exists(json, 'genre') ? undefined : json['genre'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'numberOfRatings': !exists(json, 'numberOfRatings') ? undefined : json['numberOfRatings'],
        'duration': !exists(json, 'duration') ? undefined : json['duration'],
        'actorsIds': !exists(json, 'actorsIds') ? undefined : json['actorsIds'],
        'staffMembersIds': !exists(json, 'staffMembersIds') ? undefined : json['staffMembersIds'],
    };
}

export function MovieUpdateDTOToJSON(value?: MovieUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'releaseDate': value.releaseDate === undefined ? undefined : (value.releaseDate === null ? null : value.releaseDate.toISOString()),
        'language': value.language,
        'genre': value.genre,
        'imageUrl': value.imageUrl,
        'rating': value.rating,
        'numberOfRatings': value.numberOfRatings,
        'duration': value.duration,
        'actorsIds': value.actorsIds,
        'staffMembersIds': value.staffMembersIds,
    };
}

