/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { MovieDTO } from './MovieDTO';
import {
    MovieDTOFromJSON,
    MovieDTOFromJSONTyped,
    MovieDTOToJSON,
} from './MovieDTO';

/**
 * 
 * @export
 * @interface MovieDTORequestResponse
 */
export interface MovieDTORequestResponse {
    /**
     * 
     * @type {MovieDTO}
     * @memberof MovieDTORequestResponse
     */
    response?: MovieDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof MovieDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the MovieDTORequestResponse interface.
 */
export function instanceOfMovieDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MovieDTORequestResponseFromJSON(json: any): MovieDTORequestResponse {
    return MovieDTORequestResponseFromJSONTyped(json, false);
}

export function MovieDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MovieDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : MovieDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function MovieDTORequestResponseToJSON(value?: MovieDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': MovieDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

