/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeasonAddDTO
 */
export interface SeasonAddDTO {
    /**
     * 
     * @type {number}
     * @memberof SeasonAddDTO
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof SeasonAddDTO
     */
    numberOfEpisodes?: number;
    /**
     * 
     * @type {string}
     * @memberof SeasonAddDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SeasonAddDTO
     */
    tvShowId?: string;
}

/**
 * Check if a given object implements the SeasonAddDTO interface.
 */
export function instanceOfSeasonAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SeasonAddDTOFromJSON(json: any): SeasonAddDTO {
    return SeasonAddDTOFromJSONTyped(json, false);
}

export function SeasonAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeasonAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': !exists(json, 'number') ? undefined : json['number'],
        'numberOfEpisodes': !exists(json, 'numberOfEpisodes') ? undefined : json['numberOfEpisodes'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'tvShowId': !exists(json, 'tvShowId') ? undefined : json['tvShowId'],
    };
}

export function SeasonAddDTOToJSON(value?: SeasonAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'numberOfEpisodes': value.numberOfEpisodes,
        'name': value.name,
        'tvShowId': value.tvShowId,
    };
}

