/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SeasonDTO } from './SeasonDTO';
import {
    SeasonDTOFromJSON,
    SeasonDTOFromJSONTyped,
    SeasonDTOToJSON,
} from './SeasonDTO';

/**
 * 
 * @export
 * @interface SeasonDTOPagedResponse
 */
export interface SeasonDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof SeasonDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof SeasonDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof SeasonDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<SeasonDTO>}
     * @memberof SeasonDTOPagedResponse
     */
    data?: Array<SeasonDTO> | null;
}

/**
 * Check if a given object implements the SeasonDTOPagedResponse interface.
 */
export function instanceOfSeasonDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SeasonDTOPagedResponseFromJSON(json: any): SeasonDTOPagedResponse {
    return SeasonDTOPagedResponseFromJSONTyped(json, false);
}

export function SeasonDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeasonDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(SeasonDTOFromJSON)),
    };
}

export function SeasonDTOPagedResponseToJSON(value?: SeasonDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(SeasonDTOToJSON)),
    };
}

