/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeasonAddSimpleDTO
 */
export interface SeasonAddSimpleDTO {
    /**
     * 
     * @type {number}
     * @memberof SeasonAddSimpleDTO
     */
    number?: number;
    /**
     * 
     * @type {number}
     * @memberof SeasonAddSimpleDTO
     */
    numberOfEpisodes?: number;
    /**
     * 
     * @type {string}
     * @memberof SeasonAddSimpleDTO
     */
    name?: string | null;
}

/**
 * Check if a given object implements the SeasonAddSimpleDTO interface.
 */
export function instanceOfSeasonAddSimpleDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SeasonAddSimpleDTOFromJSON(json: any): SeasonAddSimpleDTO {
    return SeasonAddSimpleDTOFromJSONTyped(json, false);
}

export function SeasonAddSimpleDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeasonAddSimpleDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'number': !exists(json, 'number') ? undefined : json['number'],
        'numberOfEpisodes': !exists(json, 'numberOfEpisodes') ? undefined : json['numberOfEpisodes'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function SeasonAddSimpleDTOToJSON(value?: SeasonAddSimpleDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'number': value.number,
        'numberOfEpisodes': value.numberOfEpisodes,
        'name': value.name,
    };
}

