/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SeasonUpdateDTO
 */
export interface SeasonUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof SeasonUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof SeasonUpdateDTO
     */
    number?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SeasonUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SeasonUpdateDTO
     */
    numberOfEpisodes?: number | null;
}

/**
 * Check if a given object implements the SeasonUpdateDTO interface.
 */
export function instanceOfSeasonUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SeasonUpdateDTOFromJSON(json: any): SeasonUpdateDTO {
    return SeasonUpdateDTOFromJSONTyped(json, false);
}

export function SeasonUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SeasonUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'number': !exists(json, 'number') ? undefined : json['number'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'numberOfEpisodes': !exists(json, 'numberOfEpisodes') ? undefined : json['numberOfEpisodes'],
    };
}

export function SeasonUpdateDTOToJSON(value?: SeasonUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'number': value.number,
        'name': value.name,
        'numberOfEpisodes': value.numberOfEpisodes,
    };
}

