/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { StaffDTO } from './StaffDTO';
import {
    StaffDTOFromJSON,
    StaffDTOFromJSONTyped,
    StaffDTOToJSON,
} from './StaffDTO';

/**
 * 
 * @export
 * @interface StaffDTORequestResponse
 */
export interface StaffDTORequestResponse {
    /**
     * 
     * @type {StaffDTO}
     * @memberof StaffDTORequestResponse
     */
    response?: StaffDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof StaffDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the StaffDTORequestResponse interface.
 */
export function instanceOfStaffDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StaffDTORequestResponseFromJSON(json: any): StaffDTORequestResponse {
    return StaffDTORequestResponseFromJSONTyped(json, false);
}

export function StaffDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : StaffDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function StaffDTORequestResponseToJSON(value?: StaffDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': StaffDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

