/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StaffDTO } from './StaffDTO';
import {
    StaffDTOFromJSON,
    StaffDTOFromJSONTyped,
    StaffDTOToJSON,
} from './StaffDTO';

/**
 * 
 * @export
 * @interface StaffDTOPagedResponse
 */
export interface StaffDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof StaffDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof StaffDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof StaffDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<StaffDTO>}
     * @memberof StaffDTOPagedResponse
     */
    data?: Array<StaffDTO> | null;
}

/**
 * Check if a given object implements the StaffDTOPagedResponse interface.
 */
export function instanceOfStaffDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StaffDTOPagedResponseFromJSON(json: any): StaffDTOPagedResponse {
    return StaffDTOPagedResponseFromJSONTyped(json, false);
}

export function StaffDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(StaffDTOFromJSON)),
    };
}

export function StaffDTOPagedResponseToJSON(value?: StaffDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(StaffDTOToJSON)),
    };
}

