/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const StaffTypeEnum = {
    Director: 'Director',
    Writer: 'Writer',
    Producer: 'Producer'
} as const;
export type StaffTypeEnum = typeof StaffTypeEnum[keyof typeof StaffTypeEnum];


export function StaffTypeEnumFromJSON(json: any): StaffTypeEnum {
    return StaffTypeEnumFromJSONTyped(json, false);
}

export function StaffTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffTypeEnum {
    return json as StaffTypeEnum;
}

export function StaffTypeEnumToJSON(value?: StaffTypeEnum | null): any {
    return value as any;
}

