/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { TvShowDTO } from './TvShowDTO';
import {
    TvShowDTOFromJSON,
    TvShowDTOFromJSONTyped,
    TvShowDTOToJSON,
} from './TvShowDTO';

/**
 * 
 * @export
 * @interface TvShowDTOPagedResponse
 */
export interface TvShowDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof TvShowDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof TvShowDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof TvShowDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<TvShowDTO>}
     * @memberof TvShowDTOPagedResponse
     */
    data?: Array<TvShowDTO> | null;
}

/**
 * Check if a given object implements the TvShowDTOPagedResponse interface.
 */
export function instanceOfTvShowDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TvShowDTOPagedResponseFromJSON(json: any): TvShowDTOPagedResponse {
    return TvShowDTOPagedResponseFromJSONTyped(json, false);
}

export function TvShowDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvShowDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(TvShowDTOFromJSON)),
    };
}

export function TvShowDTOPagedResponseToJSON(value?: TvShowDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(TvShowDTOToJSON)),
    };
}

