/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { TvShowDTOPagedResponse } from './TvShowDTOPagedResponse';
import {
    TvShowDTOPagedResponseFromJSON,
    TvShowDTOPagedResponseFromJSONTyped,
    TvShowDTOPagedResponseToJSON,
} from './TvShowDTOPagedResponse';

/**
 * 
 * @export
 * @interface TvShowDTOPagedResponseRequestResponse
 */
export interface TvShowDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {TvShowDTOPagedResponse}
     * @memberof TvShowDTOPagedResponseRequestResponse
     */
    response?: TvShowDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TvShowDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the TvShowDTOPagedResponseRequestResponse interface.
 */
export function instanceOfTvShowDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TvShowDTOPagedResponseRequestResponseFromJSON(json: any): TvShowDTOPagedResponseRequestResponse {
    return TvShowDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function TvShowDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvShowDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : TvShowDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TvShowDTOPagedResponseRequestResponseToJSON(value?: TvShowDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': TvShowDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

