/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SeasonAddSimpleDTO } from './SeasonAddSimpleDTO';
import {
    SeasonAddSimpleDTOFromJSON,
    SeasonAddSimpleDTOFromJSONTyped,
    SeasonAddSimpleDTOToJSON,
} from './SeasonAddSimpleDTO';

/**
 * 
 * @export
 * @interface TvShowUpdateDTO
 */
export interface TvShowUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof TvShowUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof TvShowUpdateDTO
     */
    accessed?: number | null;
    /**
     * 
     * @type {Array<SeasonAddSimpleDTO>}
     * @memberof TvShowUpdateDTO
     */
    seasons?: Array<SeasonAddSimpleDTO> | null;
    /**
     * 
     * @type {string}
     * @memberof TvShowUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TvShowUpdateDTO
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TvShowUpdateDTO
     */
    releaseDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof TvShowUpdateDTO
     */
    language?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TvShowUpdateDTO
     */
    genre?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TvShowUpdateDTO
     */
    imageUrl?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TvShowUpdateDTO
     */
    rating?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TvShowUpdateDTO
     */
    numberOfRatings?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TvShowUpdateDTO
     */
    actorsIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof TvShowUpdateDTO
     */
    staffMembersIds?: Array<string> | null;
}

/**
 * Check if a given object implements the TvShowUpdateDTO interface.
 */
export function instanceOfTvShowUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TvShowUpdateDTOFromJSON(json: any): TvShowUpdateDTO {
    return TvShowUpdateDTOFromJSONTyped(json, false);
}

export function TvShowUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvShowUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'accessed': !exists(json, 'accessed') ? undefined : json['accessed'],
        'seasons': !exists(json, 'seasons') ? undefined : (json['seasons'] === null ? null : (json['seasons'] as Array<any>).map(SeasonAddSimpleDTOFromJSON)),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'releaseDate': !exists(json, 'releaseDate') ? undefined : (json['releaseDate'] === null ? null : new Date(json['releaseDate'])),
        'language': !exists(json, 'language') ? undefined : json['language'],
        'genre': !exists(json, 'genre') ? undefined : json['genre'],
        'imageUrl': !exists(json, 'imageUrl') ? undefined : json['imageUrl'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'numberOfRatings': !exists(json, 'numberOfRatings') ? undefined : json['numberOfRatings'],
        'actorsIds': !exists(json, 'actorsIds') ? undefined : json['actorsIds'],
        'staffMembersIds': !exists(json, 'staffMembersIds') ? undefined : json['staffMembersIds'],
    };
}

export function TvShowUpdateDTOToJSON(value?: TvShowUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'accessed': value.accessed,
        'seasons': value.seasons === undefined ? undefined : (value.seasons === null ? null : (value.seasons as Array<any>).map(SeasonAddSimpleDTOToJSON)),
        'name': value.name,
        'description': value.description,
        'releaseDate': value.releaseDate === undefined ? undefined : (value.releaseDate === null ? null : value.releaseDate.toISOString()),
        'language': value.language,
        'genre': value.genre,
        'imageUrl': value.imageUrl,
        'rating': value.rating,
        'numberOfRatings': value.numberOfRatings,
        'actorsIds': value.actorsIds,
        'staffMembersIds': value.staffMembersIds,
    };
}

