/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { TvShowDTO } from './TvShowDTO';
import {
    TvShowDTOFromJSON,
    TvShowDTOFromJSONTyped,
    TvShowDTOToJSON,
} from './TvShowDTO';

/**
 * 
 * @export
 * @interface TvShowDTORequestResponse
 */
export interface TvShowDTORequestResponse {
    /**
     * 
     * @type {TvShowDTO}
     * @memberof TvShowDTORequestResponse
     */
    response?: TvShowDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof TvShowDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the TvShowDTORequestResponse interface.
 */
export function instanceOfTvShowDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TvShowDTORequestResponseFromJSON(json: any): TvShowDTORequestResponse {
    return TvShowDTORequestResponseFromJSONTyped(json, false);
}

export function TvShowDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TvShowDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : TvShowDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function TvShowDTORequestResponseToJSON(value?: TvShowDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': TvShowDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

