/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserMovieDTO
 */
export interface UserMovieDTO {
    /**
     * 
     * @type {string}
     * @memberof UserMovieDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserMovieDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserMovieDTO
     */
    movieId?: string;
}

/**
 * Check if a given object implements the UserMovieDTO interface.
 */
export function instanceOfUserMovieDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserMovieDTOFromJSON(json: any): UserMovieDTO {
    return UserMovieDTOFromJSONTyped(json, false);
}

export function UserMovieDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMovieDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'movieId': !exists(json, 'movieId') ? undefined : json['movieId'],
    };
}

export function UserMovieDTOToJSON(value?: UserMovieDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'movieId': value.movieId,
    };
}

