/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserMovieDTO } from './UserMovieDTO';
import {
    UserMovieDTOFromJSON,
    UserMovieDTOFromJSONTyped,
    UserMovieDTOToJSON,
} from './UserMovieDTO';
import type { UserRoleEnum } from './UserRoleEnum';
import {
    UserRoleEnumFromJSON,
    UserRoleEnumFromJSONTyped,
    UserRoleEnumToJSON,
} from './UserRoleEnum';
import type { UserTvShowDTO } from './UserTvShowDTO';
import {
    UserTvShowDTOFromJSON,
    UserTvShowDTOFromJSONTyped,
    UserTvShowDTOToJSON,
} from './UserTvShowDTO';

/**
 * 
 * @export
 * @interface UserDTO
 */
export interface UserDTO {
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    email?: string | null;
    /**
     * 
     * @type {UserRoleEnum}
     * @memberof UserDTO
     */
    role?: UserRoleEnum;
    /**
     * 
     * @type {Array<UserMovieDTO>}
     * @memberof UserDTO
     */
    favouriteMovies?: Array<UserMovieDTO> | null;
    /**
     * 
     * @type {Array<UserTvShowDTO>}
     * @memberof UserDTO
     */
    favouriteTvShows?: Array<UserTvShowDTO> | null;
}

/**
 * Check if a given object implements the UserDTO interface.
 */
export function instanceOfUserDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserDTOFromJSON(json: any): UserDTO {
    return UserDTOFromJSONTyped(json, false);
}

export function UserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'role': !exists(json, 'role') ? undefined : UserRoleEnumFromJSON(json['role']),
        'favouriteMovies': !exists(json, 'favouriteMovies') ? undefined : (json['favouriteMovies'] === null ? null : (json['favouriteMovies'] as Array<any>).map(UserMovieDTOFromJSON)),
        'favouriteTvShows': !exists(json, 'favouriteTvShows') ? undefined : (json['favouriteTvShows'] === null ? null : (json['favouriteTvShows'] as Array<any>).map(UserTvShowDTOFromJSON)),
    };
}

export function UserDTOToJSON(value?: UserDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
        'role': UserRoleEnumToJSON(value.role),
        'favouriteMovies': value.favouriteMovies === undefined ? undefined : (value.favouriteMovies === null ? null : (value.favouriteMovies as Array<any>).map(UserMovieDTOToJSON)),
        'favouriteTvShows': value.favouriteTvShows === undefined ? undefined : (value.favouriteTvShows === null ? null : (value.favouriteTvShows as Array<any>).map(UserTvShowDTOToJSON)),
    };
}

