/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserTvShowDTO
 */
export interface UserTvShowDTO {
    /**
     * 
     * @type {string}
     * @memberof UserTvShowDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTvShowDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserTvShowDTO
     */
    tvShowId?: string;
}

/**
 * Check if a given object implements the UserTvShowDTO interface.
 */
export function instanceOfUserTvShowDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserTvShowDTOFromJSON(json: any): UserTvShowDTO {
    return UserTvShowDTOFromJSONTyped(json, false);
}

export function UserTvShowDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserTvShowDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'tvShowId': !exists(json, 'tvShowId') ? undefined : json['tvShowId'],
    };
}

export function UserTvShowDTOToJSON(value?: UserTvShowDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'tvShowId': value.tvShowId,
    };
}

